# Generated by Django 5.2.7 on 2025-11-13 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParkingLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "base_image",
                    models.ImageField(blank=True, null=True, upload_to="layouts/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParkingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_name", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("empty_count", models.IntegerField(default=0)),
                ("occupied_count", models.IntegerField(default=0)),
                (
                    "annotated_image",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="api.parkinglot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParkingDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cls_name", models.CharField(max_length=32)),
                ("confidence", models.FloatField(default=1.0)),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("w", models.IntegerField()),
                ("h", models.IntegerField()),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="api.parkinglot",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="api.parkingsnapshot",
                    ),
                ),
            ],
        ),
    ]
