# Generated by Django 5.2.7 on 2025-10-31 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_parkingsnapshot_annotated_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cls_name", models.CharField(max_length=32)),
                ("conf", models.FloatField(default=0.0)),
                ("cx_norm", models.FloatField()),
                ("cy_norm", models.FloatField()),
                ("w_norm", models.FloatField(blank=True, null=True)),
                ("h_norm", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="api.parkingsnapshot",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="api_parking_created_f8f978_idx"
                    ),
                    models.Index(
                        fields=["cls_name"], name="api_parking_cls_nam_6860bc_idx"
                    ),
                ],
            },
        ),
    ]
