"""
Django settings for smartparking project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path

# ----------------------------------------
# Basic Paths
# ----------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------------------------
# Security
# ----------------------------------------
SECRET_KEY = 'django-insecure-bexw&3(8k(jr9m8nz36b5n^uovh@==sd_%0o+15!7%y1r#)ne1'
DEBUG = True
ALLOWED_HOSTS = ["*"]

# ----------------------------------------
# Installed Apps
# ----------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',   # add CORS first
    'api',
]

# ----------------------------------------
# Middleware
# ----------------------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # must be first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ----------------------------------------
# CORS (allow React frontend to connect)
# ----------------------------------------
CORS_ALLOW_ALL_ORIGINS = True  # For development (React @ localhost:3000)
# If you prefer to restrict:
# CORS_ALLOWED_ORIGINS = ["http://localhost:3000"]

# ----------------------------------------
# Root and Templates
# ----------------------------------------
ROOT_URLCONF = 'smartparking.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartparking.wsgi.application'

# ----------------------------------------
# Database (PostgreSQL in Docker)
# ----------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'parkingdb'),
        'USER': os.environ.get('POSTGRES_USER', 'parkinguser'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'parkingpass'),
        'HOST': os.environ.get('POSTGRES_HOST', 'db'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}

# ----------------------------------------
# Password Validation
# ----------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ----------------------------------------
# Internationalization
# ----------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ----------------------------------------
# Static & Media Files
# ----------------------------------------
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Local Media setup (for uploads & YOLO results)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# ----------------------------------------
# Optional: MinIO / S3 Configuration (disabled for now)
# ----------------------------------------
USE_S3 = os.environ.get("USE_S3", "False").lower() == "true"

if USE_S3:
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    AWS_S3_ENDPOINT_URL = "http://minio:9000"
    MINIO_PUBLIC_ENDPOINT = "http://localhost:9000"
    AWS_ACCESS_KEY_ID = os.environ.get("MINIO_ACCESS_KEY")
    AWS_SECRET_ACCESS_KEY = os.environ.get("MINIO_SECRET_KEY")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("MINIO_BUCKET_NAME")
    AWS_S3_REGION_NAME = None
    AWS_S3_USE_SSL = os.environ.get("MINIO_USE_SSL", "False").lower() == "true"

# ----------------------------------------
# Default Primary Key Type
# ----------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
